#!/usr/bin/dash

# xorg stuff
[ -f "$HOME"/.Xresources ] && hash xrdb && xrdb -merge "$HOME"/.Xresources&
[ -f "$HOME"/.Xmodmap ] && hash xmodmap && xmodmap "$HOME"/.Xmodmap&

for _sx in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$_sx" ] && . "$_sx";
done&

startdwm;

# vim: ft=sh
