#!/usr/bin/dash

dunst&
"$HOME"/.local/bin/dwmstatus&
# urxvtd -q -f -o&
# { emacs --daemon && notify-send "Emacs daemon loaded"; }&
# nm-applet&
# redshift -r -P&
# oneko -tomoyo -tofocus -fg '#282a36' -bg '#ff79c6' -speed 40 -idle 500 -position -35-35&

if [ -f /etc/X11/xinit/.Xresources ]; then xrdb -merge "$HOME"/.Xresources; fi&
if [ -f "$HOME"/.Xresources ]; then xrdb -merge "$HOME"/.Xresources; fi&
if [ -f /etc/X11/xinit/.Xmodmap ]; then xmodmap "$HOME"/.Xmodmap; fi&
if [ -f "$HOME"/.Xmodmap ]; then xmodmap "$HOME"/.Xmodmap; fi&
for x in /etc/X11/xinit/xinitrc.d/?*.sh; do [ -x "$x" ] && . "$x"; done&

_dwm(){
  # picom -b&
  "$HOME"/.local/bin/mouse_kbd_setup&
  "$HOME"/.fehbg&
  while :; do
    dwm;
    [ $? = 137 ] || break;
    . ""$HOME"/.zprofile"
  done;
  return $x;
};
_dwm;
exit $?;

# vim: ft=sh
